name: Deployment
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - uses: actions/checkout@v3
        - uses: SpicyPizza/create-envfile@v1.3  
          with:
            envkey_ENV_COUNTING_CHANNEL: ${{ secrets.COUNTING_CHANNEL }}
            envkey_ENV_MESSAGE_CHANNEL: ${{ secrets.MESSAGE_CHANNEL }}
            envkey_ENV_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        - run: flyctl deploy --remote-only
